# Generated by Django 4.2.14 on 2025-02-02 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('category', models.CharField(choices=[('tko', 'ТКО'), ('closed', 'Закрытая'), ('radio', 'Радио'), ('computer', 'СВТ'), ('battery', 'АКБ'), ('antenna', 'Антенны, мачты'), ('power', 'Источники питания'), ('materials', 'Материалы')], max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('in-operation', 'Эксплуатируется'), ('in-storage', 'На складе'), ('defective', 'Неисправно'), ('for-disposal', 'На списание')], max_length=20, verbose_name='Статус')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(max_length=255, verbose_name='Инвентарный номер')),
                ('manufacturing_date', models.DateField(verbose_name='Дата производства')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('subdivision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отделение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['name'],
            },
        ),
    ]
