# Generated by Django 4.2.14 on 2025-02-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('equipment', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='users.user', verbose_name='Закреплено за'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='facilities.division', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='facilities.facility', verbose_name='Объект'),
        ),
    ]
