# Generated by Django 4.2.14 on 2025-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='disposal_act_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта списания'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='disposal_act_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='№ акта списания'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='disposal_cert_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата справки о ликвидации'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='disposal_cert_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='№ справки о ликвидации'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='disposal_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к списанию'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in-operation', 'Эксплуатируется'), ('in-storage', 'На складе'), ('defective', 'Неисправно'), ('for-disposal', 'На списание'), ('disposed', 'Списано')], max_length=20, verbose_name='Статус'),
        ),
    ]
