# Generated by Django 4.2.14 on 2025-03-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория закрытой техники',
                'verbose_name_plural': 'Категории закрытой техники',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрытая техника'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='open_category',
            field=models.CharField(blank=True, choices=[('tko', 'ТКО'), ('radio', 'Радио'), ('computer', 'СВТ'), ('battery', 'АКБ'), ('antenna', 'Антенны, мачты'), ('power', 'Источники питания'), ('materials', 'Материалы')], max_length=20, null=True, verbose_name='Категория (открытая техника)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='closed_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.closedequipmentcategory', verbose_name='Категория (закрытая техника)'),
        ),
    ]
