# Generated by Django 4.2.14 on 2025-03-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_employee_subdivision'),
        ('equipment', '0005_closedequipmentcategory_remove_equipment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='users.employee', verbose_name='Закреплено за'),
        ),
    ]
