# Generated by Django 4.2.14 on 2025-03-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_remove_division_staff_actual_and_more'),
        ('equipment', '0006_alter_equipment_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='facilities.subdivision', verbose_name='Отделение'),
        ),
    ]
