# Generated by Django 4.2.14 on 2025-04-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipment_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория открытой техники',
                'verbose_name_plural': 'Категории закрытой техники',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='open_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.openequipmentcategory', verbose_name='Категория (открытая техника)'),
        ),
    ]
