# Generated by Django 4.2.14 on 2025-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_openequipmentcategory_alter_equipment_open_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openequipmentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория открытой техники', 'verbose_name_plural': 'Категории открытой техники'},
        ),
        migrations.AddField(
            model_name='openequipmentcategory',
            name='value',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Код категории'),
        ),
    ]
