# Generated by Django 4.2.14 on 2025-04-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_openequipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openequipmentcategory',
            name='value',
        ),
    ]
