# Generated by Django 4.2.14 on 2025-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_remove_openequipmentcategory_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='openequipmentcategory',
            name='value',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Код категории'),
        ),
    ]
