# Generated by Django 4.2.14 on 2025-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_openequipmentcategory_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['division'], name='equipment_e_divisio_5df752_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['subdivision'], name='equipment_e_subdivi_788d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['facility'], name='equipment_e_facilit_0c19b7_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['assigned_to'], name='equipment_e_assigne_96ad0d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_closed'], name='equipment_e_is_clos_3bd0f6_idx'),
        ),
    ]
