# Generated by Django 4.2.14 on 2025-05-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_equipment_equipment_e_divisio_5df752_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedequipmentcategory',
            name='value',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Код категории'),
        ),
    ]
