# Generated by Django 4.2.14 on 2025-05-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_closedequipmentcategory_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='first_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первичный документ на получение'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='material_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Накладная на МОЛ'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ver_software',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Версия программного обеспечения'),
        ),
        migrations.CreateModel(
            name='ProductStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заводской номер')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_structures', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Состав изделия',
                'verbose_name_plural': 'Составы изделий',
                'ordering': ['name'],
            },
        ),
    ]
