# Generated by Django 4.2.14 on 2025-08-15 08:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_equipment_first_invoice_equipment_material_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('netmask', models.CharField(max_length=39, verbose_name='Маска/префикс')),
                ('version', models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=4, verbose_name='Версия IP')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной адрес')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='Шлюз')),
                ('dns_servers', models.TextField(blank=True, verbose_name='DNS-серверы')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'IP-адрес',
                'verbose_name_plural': 'IP-адреса',
            },
        ),
        migrations.CreateModel(
            name='IPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=43, verbose_name='Сеть')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Диапазон IP',
                'verbose_name_plural': 'Диапазоны IP',
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('interface_type', models.CharField(choices=[('physical', 'Физический порт'), ('vlan', 'VLAN Interface'), ('loopback', 'Loopback'), ('port-channel', 'Port-Channel'), ('tunnel', 'Tunnel'), ('other', 'Другой')], default='physical', max_length=20, verbose_name='Тип')),
                ('physical_type', models.CharField(blank=True, choices=[('rj45', 'RJ-45'), ('sfp', 'SFP'), ('sfp+', 'SFP+'), ('qsfp', 'QSFP'), ('console', 'Console'), ('usb', 'USB')], max_length=20, null=True, verbose_name='Тип порта')),
                ('port_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер порта')),
                ('slot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Слот')),
                ('module', models.PositiveIntegerField(blank=True, null=True, verbose_name='Модуль')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC-адрес')),
                ('mtu', models.PositiveIntegerField(default=1500, verbose_name='MTU')),
                ('speed', models.CharField(blank=True, max_length=20, verbose_name='Скорость')),
                ('is_trunk', models.BooleanField(default=False, verbose_name='Trunk порт')),
            ],
            options={
                'verbose_name': 'Сетевой интерфейс',
                'verbose_name_plural': 'Сетевые интерфейсы',
                'ordering': ['equipment', 'slot', 'module', 'port_number'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)], verbose_name='VLAN ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название VLAN')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
                'ordering': ['vlan_id'],
            },
        ),
        migrations.AddField(
            model_name='closedequipmentcategory',
            name='is_network',
            field=models.BooleanField(default=False, verbose_name='Сетевое оборудование'),
        ),
        migrations.AddField(
            model_name='openequipmentcategory',
            name='is_network',
            field=models.BooleanField(default=False, verbose_name='Сетевое оборудование'),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(fields=('vlan_id',), name='unique_vlan_id'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='connected_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.networkinterface', verbose_name='Подключен к'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='native_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_interfaces', to='equipment.vlan', verbose_name='Native VLAN'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.vlan', verbose_name='Access VLAN'),
        ),
        migrations.AddField(
            model_name='iprange',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='ip_ranges', to='equipment.equipment', verbose_name='Устройства'),
        ),
        migrations.AddField(
            model_name='iprange',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_ranges', to='equipment.vlan', verbose_name='VLAN'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='equipment.networkinterface', verbose_name='Интерфейс'),
        ),
    ]
