# Generated by Django 4.2.14 on 2025-08-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_ipaddress_iprange_networkinterface_vlan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iprange',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='iprange',
            name='vlan',
        ),
        migrations.RemoveField(
            model_name='networkinterface',
            name='connected_to',
        ),
        migrations.RemoveField(
            model_name='networkinterface',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='networkinterface',
            name='native_vlan',
        ),
        migrations.RemoveField(
            model_name='networkinterface',
            name='vlan',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.DeleteModel(
            name='IPRange',
        ),
        migrations.DeleteModel(
            name='NetworkInterface',
        ),
        migrations.DeleteModel(
            name='VLAN',
        ),
    ]
