# Generated by Django 4.2.14 on 2025-08-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_remove_iprange_devices_remove_iprange_vlan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedequipmentcategory',
            name='is_network',
        ),
        migrations.RemoveField(
            model_name='openequipmentcategory',
            name='is_network',
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_network',
            field=models.BooleanField(default=False, verbose_name='Сетевое оборудование'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_network'], name='equipment_e_is_netw_0cdd4e_idx'),
        ),
    ]
