# Generated by Django 4.2.14 on 2025-08-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_remove_closedequipmentcategory_is_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, null=True, unique=True, verbose_name='Код категории')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Для закрытой техники')),
            ],
            options={
                'verbose_name': 'Категория техники',
                'verbose_name_plural': 'Категории техники',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='closed_category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='open_category',
        ),
        migrations.DeleteModel(
            name='ClosedEquipmentCategory',
        ),
        migrations.DeleteModel(
            name='OpenEquipmentCategory',
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentcategory', verbose_name='Категория техники'),
        ),
    ]
