# Generated by Django 4.2.14 on 2025-08-29 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_equipmentcategory_remove_equipment_closed_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['created_at'], 'verbose_name': 'Категория техники', 'verbose_name_plural': 'Категории техники'},
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
