# Generated by Django 4.2.14 on 2025-09-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_ipaddress_iprange_networkinterface_vlan_and_more'),
        ('equipment', '0021_alter_equipment_exploitation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip_addresses',
            field=models.ManyToManyField(blank=True, related_name='equipment_ip_addresses', to='networks.ipaddress', verbose_name='IP-адреса'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='network_interfaces',
            field=models.ManyToManyField(blank=True, related_name='net_network_interfaces', to='networks.networkinterface', verbose_name='Сетевые интерфейсы'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='vlans',
            field=models.ManyToManyField(blank=True, related_name='equipment_vlans', to='networks.vlan', verbose_name='VLANы'),
        ),
    ]
