# Generated by Django 4.2.14 on 2025-09-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_communicationpost_description'),
        ('equipment', '0022_equipment_ip_addresses_equipment_network_interfaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='facilities.division', verbose_name='Подразделение'),
        ),
    ]
