# Generated by Django 4.2.14 on 2025-09-29 00:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_communicationpost_description'),
        ('equipment', '0025_alter_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='free_use_act_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер акта приема-передачи в безвозмездное пользование'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_free_use',
            field=models.BooleanField(default=False, verbose_name='Выдана в безвозмездное пользование'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='secret_level',
            field=models.CharField(blank=True, choices=[('OV', 'ОВ'), ('SS', 'СС'), ('SECRET', 'Секретно'), ('DSP', 'ДСП')], max_length=20, null=True, verbose_name='Степень секретности'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_life',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок службы'),
        ),
        migrations.CreateModel(
            name='InterestOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование органа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_organs', to='facilities.division', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Орган интересов',
                'verbose_name_plural': 'Органы интересов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='interest_organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.interestorgan', verbose_name='В чьих интересах эксплуатируется'),
        ),
    ]
