# Generated by Django 4.2.14 on 2025-09-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0026_equipment_free_use_act_number_equipment_is_free_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestorgan',
            name='division',
        ),
    ]
