# Generated by Django 4.2.14 on 2026-02-04 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('equipment', '0027_remove_interestorgan_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='employees.employee', verbose_name='Закреплено за'),
        ),
    ]
