# Generated by Django 4.2.14 on 2025-12-02 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0030_alter_communicationpost_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='FileShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Токен доступа')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('max_downloads', models.IntegerField(blank=True, null=True, verbose_name='Макс. скачиваний')),
                ('download_count', models.IntegerField(default=0, verbose_name='Скачано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Ссылка для общего доступа',
                'verbose_name_plural': 'Ссылки для общего доступа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='storagefile',
            options={'ordering': ['is_pinned', '-created_at'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='storagefolder',
            options={'ordering': ['is_pinned', '-created_at'], 'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
        migrations.AddField(
            model_name='storagefile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Удалил'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='facilities.division', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='extension',
            field=models.CharField(default='', max_length=50, verbose_name='Расширение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagefile',
            name='file_type',
            field=models.CharField(choices=[('personal', 'Личное'), ('work', 'Рабочее')], default='work', max_length=10, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее скачивание'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='original_name',
            field=models.CharField(default='', max_length=255, verbose_name='Оригинальное имя файла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagefile',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='facilities.subdivision', verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='color',
            field=models.CharField(default='#1976D2', max_length=7, verbose_name='Цвет папки'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Удалил'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='facilities.division', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='folder_type',
            field=models.CharField(choices=[('personal', 'Личное'), ('work', 'Рабочее')], default='work', max_length=10, verbose_name='Тип папки'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
        migrations.AddField(
            model_name='storagefolder',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='facilities.subdivision', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='file',
            field=models.FileField(upload_to='storage/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='size',
            field=models.BigIntegerField(verbose_name='Размер (байты)'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['file_type', 'is_deleted'], name='storage_sto_file_ty_4dfc51_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['mime_type'], name='storage_sto_mime_ty_685888_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['division', 'subdivision'], name='storage_sto_divisio_00729d_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefolder',
            index=models.Index(fields=['folder_type', 'is_deleted'], name='storage_sto_folder__a1d93c_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefolder',
            index=models.Index(fields=['division', 'subdivision'], name='storage_sto_divisio_84a260_idx'),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='storage.storagefile', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='storage.storagefile', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='storage.storagefolder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(check=models.Q(('folder__isnull', False), ('file__isnull', False), _connector='OR'), name='either_folder_or_file'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'folder'), ('user', 'file')},
        ),
    ]
