# Generated by Django 4.2.14 on 2025-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='acceptance_act_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер акта приемки помещения'),
        ),
        migrations.AddField(
            model_name='facility',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='facility',
            name='commissioning_act_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер акта ввода'),
        ),
        migrations.AddField(
            model_name='facility',
            name='has_grounding_in_kz',
            field=models.BooleanField(default=False, verbose_name='Контур заземления в пределах КЗ'),
        ),
        migrations.AddField(
            model_name='facility',
            name='has_transformer_in_kz',
            field=models.BooleanField(default=False, verbose_name='ТП в пределах КЗ'),
        ),
        migrations.AddField(
            model_name='facility',
            name='kz_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер КЗ'),
        ),
        migrations.AddField(
            model_name='facility',
            name='opening_permission_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер разрешения на открытие'),
        ),
        migrations.AddField(
            model_name='facility',
            name='rim_act_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер акта РИМ'),
        ),
    ]
