# Generated by Django 4.2.14 on 2025-03-24 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_acceptance_act_number_facility_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='staff_civilians',
            field=models.PositiveIntegerField(default=0, verbose_name='Гражданский персонал (штат)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_command',
            field=models.PositiveIntegerField(default=0, verbose_name='Руководство (штат)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_officers',
            field=models.PositiveIntegerField(default=0, verbose_name='Офицеры (штат)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Полная штатная численность'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_warrant_officers',
            field=models.PositiveIntegerField(default=0, verbose_name='Прапорщики (штат)'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название отдела'),
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отделения')),
                ('staff_total', models.PositiveIntegerField(default=0, verbose_name='Полная штатная численность')),
                ('staff_command', models.PositiveIntegerField(default=0, verbose_name='Руководство (штат)')),
                ('staff_officers', models.PositiveIntegerField(default=0, verbose_name='Офицеры (штат)')),
                ('staff_warrant_officers', models.PositiveIntegerField(default=0, verbose_name='Прапорщики (штат)')),
                ('staff_civilians', models.PositiveIntegerField(default=0, verbose_name='Гражданский персонал (штат)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='facilities.division', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['division', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='facility',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='facilities.subdivision', verbose_name='Отделение'),
        ),
    ]
