# Generated by Django 4.2.14 on 2025-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_employee_is_command_alter_employee_birth_date_and_more'),
        ('facilities', '0003_division_staff_civilians_division_staff_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='staff_civilians',
        ),
        migrations.RemoveField(
            model_name='division',
            name='staff_command',
        ),
        migrations.RemoveField(
            model_name='division',
            name='staff_officers',
        ),
        migrations.RemoveField(
            model_name='division',
            name='staff_total',
        ),
        migrations.RemoveField(
            model_name='division',
            name='staff_warrant_officers',
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='subdivision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отделение'),
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
    ]
