# Generated by Django 4.2.14 on 2025-03-27 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_division_staff_civilians_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='staff_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат сотрудников (факт)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_planned',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат сотрудников (план)'),
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_planned', models.PositiveIntegerField(default=0, verbose_name='Штат сотрудников (план)')),
                ('staff_actual', models.PositiveIntegerField(default=0, verbose_name='Штат сотрудников (факт)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='facilities.division')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='facility',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='facilities.subdivision', verbose_name='Отделение'),
        ),
    ]
