# Generated by Django 4.2.14 on 2025-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_division_staff_actual_division_staff_planned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='staff_actual',
        ),
        migrations.RemoveField(
            model_name='division',
            name='staff_planned',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='staff_actual',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='staff_planned',
        ),
        migrations.AddField(
            model_name='division',
            name='staff_planned_civilian',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат гражданского персонала (план)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_planned_management',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат руководства (план)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_planned_officers',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат офицеров (план)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_planned_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий штат сотрудников (план)'),
        ),
        migrations.AddField(
            model_name='division',
            name='staff_planned_warrant_officers',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат прапорщиков (план)'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='staff_planned_civilian',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат гражданского персонала (план)'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='staff_planned_management',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат руководства (план)'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='staff_planned_officers',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат офицеров (план)'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='staff_planned_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий штат сотрудников (план)'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='staff_planned_warrant_officers',
            field=models.PositiveIntegerField(default=0, verbose_name='Штат прапорщиков (план)'),
        ),
    ]
