# Generated by Django 4.2.14 on 2025-04-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_remove_division_staff_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='facilities.division'),
        ),
    ]
