# Generated by Django 4.2.14 on 2025-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_alter_subdivision_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрытый объект'),
        ),
    ]
