# Generated by Django 4.2.14 on 2025-05-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_facility_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='communication_posts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Посты связи'),
        ),
        migrations.AddField(
            model_name='facility',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
    ]
