# Generated by Django 4.2.14 on 2025-05-08 01:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_facility_communication_posts_facility_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='communication_posts',
        ),
        migrations.CreateModel(
            name='CommunicationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование поста связи')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_posts', to='facilities.division', verbose_name='Подразделение')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_posts', to='facilities.subdivision', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Пост связи',
                'verbose_name_plural': 'Посты связи',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='communication_posts',
            field=models.ManyToManyField(blank=True, to='facilities.communicationpost', verbose_name='Посты связи'),
        ),
    ]
