# Generated by Django 4.2.14 on 2025-05-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_remove_facility_communication_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='communication_posts',
            field=models.ManyToManyField(blank=True, null=True, to='facilities.communicationpost', verbose_name='Посты связи'),
        ),
    ]
