# Generated by Django 4.2.14 on 2025-05-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_alter_facility_communication_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='communication_posts',
            field=models.ManyToManyField(blank=True, to='facilities.communicationpost', verbose_name='Посты связи'),
        ),
    ]
