# Generated by Django 4.2.14 on 2025-05-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_alter_facility_communication_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_class',
            field=models.CharField(blank=True, choices=[('1', '1 класс'), ('2', '2 класс')], max_length=1, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(blank=True, choices=[('station', 'Станция'), ('shd', 'ШД')], max_length=10, null=True, verbose_name='Тип объекта'),
        ),
    ]
