# Generated by Django 4.2.14 on 2025-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_alter_facility_address_alter_facility_facility_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(blank=True, choices=[('station', 'Станция'), ('shd', 'ШД'), ('kps', 'Комплексный'), ('prm', 'Приемный центр'), ('prm', 'Передающий центр'), ('laz', 'ЛАЗ'), ('dzl', 'Дизельная'), ('dzl', 'Спутник')], max_length=10, null=True, verbose_name='Тип объекта'),
        ),
    ]
