# Generated by Django 4.2.14 on 2025-06-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_alter_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='facility',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='facility',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Полный адрес'),
        ),
    ]
