# Generated by Django 4.2.14 on 2025-06-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0016_facilitytype_alter_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.facilitytype', verbose_name='Тип объекта'),
        ),
    ]
