# Generated by Django 4.2.14 on 2025-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0020_remove_facilitytype_value_alter_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Значение'),
        ),
    ]
