# Generated by Django 4.2.14 on 2025-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0021_facilitytype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationpost',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Значение'),
        ),
    ]
