# Generated by Django 4.2.14 on 2025-06-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0022_alter_communicationpost_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationpost',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_posts_values', to='facilities.facilitytype', verbose_name='Тип объекта'),
        ),
    ]
