# Generated by Django 4.2.14 on 2025-06-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0023_alter_communicationpost_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytype',
            name='value',
        ),
    ]
