# Generated by Django 4.2.14 on 2025-06-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0024_remove_facilitytype_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationpost',
            name='value',
        ),
    ]
