# Generated by Django 4.2.14 on 2025-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0025_remove_communicationpost_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationpost',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
