# Generated by Django 4.2.14 on 2025-10-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_communicationpost_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='division',
            name='order',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки'),
        ),
    ]
