# Generated by Django 4.2.14 on 2025-10-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0027_alter_division_options_division_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Отделение', 'verbose_name_plural': 'Отделения'},
        ),
        migrations.AddField(
            model_name='subdivision',
            name='order',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки'),
        ),
    ]
