# Generated by Django 4.2.14 on 2025-11-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0028_alter_subdivision_options_subdivision_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationpost',
            options={'verbose_name': 'Пост связи', 'verbose_name_plural': 'Посты связи'},
        ),
        migrations.AlterField(
            model_name='communicationpost',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_posts', to='facilities.subdivision', verbose_name='Отделение'),
        ),
    ]
