# Generated by Django 4.2.14 on 2025-12-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0029_alter_communicationpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationpost',
            options={'ordering': ['name'], 'verbose_name': 'Пост связи', 'verbose_name_plural': 'Посты связи'},
        ),
    ]
