# Generated by Django 4.2.14 on 2026-02-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0030_alter_communicationpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='is_closed_type',
            field=models.BooleanField(default=False, verbose_name='Закрытый тип'),
        ),
    ]
