# Generated by Django 4.2.14 on 2026-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0031_add_is_closed_type_to_facilitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
