# Generated by Django 4.2.14 on 2026-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0032_facilitytype_latitude_facilitytype_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytype',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='facilitytype',
            name='longitude',
        ),
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
