# Generated by Django 4.2.14 on 2026-07-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('facilities', '0033_remove_facilitytype_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='deputy_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_headed_divisions', to='employees.employee', verbose_name='Заместитель начальника отдела'),
        ),
        migrations.AddField(
            model_name='division',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_divisions', to='employees.employee', verbose_name='Начальник отдела'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='deputy_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_headed_subdivisions', to='employees.employee', verbose_name='Заместитель начальника отделения'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_subdivisions', to='employees.employee', verbose_name='Начальник отделения'),
        ),
    ]
