# Generated by Django 4.2.14 on 2025-11-04 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RussianRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название региона')),
                ('capital', models.CharField(max_length=255, verbose_name='Административный центр')),
                ('population', models.CharField(blank=True, max_length=100, null=True, verbose_name='Население')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Площадь')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Регион РФ',
                'verbose_name_plural': 'Регионы РФ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FSBOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование органа')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('region', models.CharField(db_index=True, max_length=255, verbose_name='Регион')),
                ('phone_operator', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон оперативного дежурного')),
                ('phone_communication', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон дежурного по связи')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Факс должен быть в формате: '+79999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Факс')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Территориальный орган ФСБ',
                'verbose_name_plural': 'Территориальные органы ФСБ',
                'ordering': ['region', 'name'],
                'indexes': [models.Index(fields=['region'], name='map_fsboffi_region_ffc9ff_idx'), models.Index(fields=['is_active'], name='map_fsboffi_is_acti_8f3df3_idx')],
            },
        ),
    ]
