# Generated by Django 4.2.14 on 2025-11-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_fsboffice_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsboffice',
            name='phone_communication',
            field=models.CharField(max_length=20, verbose_name='Телефон дежурного по связи'),
        ),
    ]
