# Generated by Django 4.2.14 on 2025-11-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_fsboffice_phone_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsboffice',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='fsboffice',
            name='phone_operator',
            field=models.CharField(max_length=20, verbose_name='Телефон оперативного дежурного'),
        ),
    ]
