# Generated by Django 4.2.14 on 2026-02-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_fsboffice_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsboffice',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='fsboffice',
            name='phone_communication',
            field=models.CharField(max_length=100, verbose_name='Телефон дежурного по связи'),
        ),
        migrations.AlterField(
            model_name='fsboffice',
            name='phone_operator',
            field=models.CharField(max_length=100, verbose_name='Телефон оперативного дежурного'),
        ),
    ]
