# Generated by Django 4.2.14 on 2025-06-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_communicationpost_description'),
        ('users', '0026_alter_employee_order_rank'),
        ('tasks', '0003_task_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='users.user', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='facilities.subdivision', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
