# Generated by Django 4.2.14 on 2025-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_created_at_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватная задача'),
        ),
    ]
