# Generated by Django 4.2.14 on 2025-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0026_communicationpost_description'),
        ('equipment', '0014_equipment_first_invoice_equipment_material_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сети')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('network_class', models.CharField(choices=[('A', 'Класс A'), ('B', 'Класс B'), ('C', 'Класс C'), ('D', 'Класс D')], max_length=1, verbose_name='Класс сети')),
                ('security_level', models.CharField(choices=[('public', 'Открытая'), ('confidential', 'Конфиденциальная'), ('secret', 'Секретная'), ('top_secret', 'Совершенно секретная')], max_length=20, verbose_name='Степень секретности информации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('divisions', models.ManyToManyField(blank=True, to='facilities.division', verbose_name='Подразделения')),
                ('equipment', models.ManyToManyField(blank=True, to='equipment.equipment', verbose_name='Техника')),
                ('facilities', models.ManyToManyField(blank=True, to='facilities.facility', verbose_name='Объекты')),
                ('subdivisions', models.ManyToManyField(blank=True, to='facilities.subdivision', verbose_name='Отделения')),
            ],
        ),
    ]
