# Generated by Django 4.2.14 on 2025-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_equipment_first_invoice_equipment_material_invoice_and_more'),
        ('facilities', '0026_communicationpost_description'),
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationnetwork',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='communication_networks', to='facilities.division', verbose_name='Подразделения'),
        ),
        migrations.AlterField(
            model_name='communicationnetwork',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='communication_networks', to='equipment.equipment', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='communicationnetwork',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='communication_networks', to='facilities.facility', verbose_name='Объекты'),
        ),
        migrations.AlterField(
            model_name='communicationnetwork',
            name='subdivisions',
            field=models.ManyToManyField(blank=True, related_name='communication_networks', to='facilities.subdivision', verbose_name='Отделения'),
        ),
    ]
