# Generated by Django 4.2.14 on 2025-08-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_alter_communicationnetwork_divisions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationnetwork',
            options={'ordering': ['name'], 'verbose_name': 'Сеть связи', 'verbose_name_plural': 'Сети связи'},
        ),
        migrations.AddField(
            model_name='communicationnetwork',
            name='bandwidth',
            field=models.CharField(blank=True, help_text='Например: 1Gbps, 100Mbps', max_length=50, verbose_name='Пропускная способность'),
        ),
        migrations.AddField(
            model_name='communicationnetwork',
            name='ip_range',
            field=models.CharField(blank=True, help_text='Формат: 192.168.1.0/24', max_length=100, verbose_name='IP диапазон'),
        ),
        migrations.AddField(
            model_name='communicationnetwork',
            name='protocol',
            field=models.CharField(choices=[('TCP/IP', 'TCP/IP'), ('UDP', 'UDP'), ('MPLS', 'MPLS'), ('Other', 'Другой')], default='TCP/IP', max_length=20, verbose_name='Протокол связи'),
        ),
        migrations.AddField(
            model_name='communicationnetwork',
            name='throughput',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пропускная способность (Mbps)'),
        ),
        migrations.AlterField(
            model_name='communicationnetwork',
            name='network_class',
            field=models.CharField(choices=[('1', '1 класс'), ('2', '2 класс')], max_length=1, verbose_name='Класс сети'),
        ),
    ]
