# Generated by Django 4.2.14 on 2025-08-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_alter_communicationnetwork_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationnetwork',
            name='bandwidth',
        ),
    ]
