# Generated by Django 4.2.14 on 2025-08-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_remove_communicationnetwork_bandwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationnetwork',
            name='network_class',
            field=models.CharField(blank=True, choices=[('1', '1 класс'), ('2', '2 класс')], max_length=1, null=True, verbose_name='Класс сети'),
        ),
    ]
