# Generated by Django 4.2.14 on 2025-08-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_alter_communicationnetwork_network_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationnetwork',
            name='security_level',
            field=models.CharField(choices=[('Открытая', 'public'), ('Конфиденциальная', 'confidential'), ('Секретная', 'secret'), ('Совершенно секретная', 'top_secret')], max_length=20, verbose_name='Степень секретности информации'),
        ),
    ]
