# Generated by Django 4.2.14 on 2025-08-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_alter_communicationnetwork_security_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationnetwork',
            name='security_level',
            field=models.CharField(choices=[('public', 'Открытая'), ('confidential', 'Конфиденциальная'), ('secret', 'Секретная'), ('top_secret', 'Совершенно секретная')], max_length=20, verbose_name='Степень секретности информации'),
        ),
    ]
