# Generated by Django 4.2.14 on 2025-09-01 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_equipment_ip_addresses_equipment_network_interfaces_and_more'),
        ('networks', '0008_ipaddress_iprange_networkinterface_vlan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_interfaces', to='equipment.equipment', verbose_name='Оборудование'),
        ),
    ]
