# Generated by Django 4.2.14 on 2025-09-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_equipment_ip_addresses_equipment_network_interfaces_and_more'),
        ('networks', '0009_alter_networkinterface_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='access_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_ports', to='networks.vlan', verbose_name='Access VLAN'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='connected_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_interfaces', to='equipment.equipment', verbose_name='Подключенное устройство'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='mode',
            field=models.CharField(choices=[('access', 'Access'), ('trunk', 'Trunk'), ('general', 'General'), ('hybrid', 'Hybrid')], default='access', max_length=10, verbose_name='Режим порта'),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='native_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_ports', to='networks.vlan', verbose_name='Native VLAN'),
        ),
        migrations.AlterUniqueTogether(
            name='networkinterface',
            unique_together={('equipment', 'name')},
        ),
        migrations.CreateModel(
            name='RoutingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=43, verbose_name='Сеть назначения')),
                ('netmask', models.CharField(max_length=39, verbose_name='Маска сети')),
                ('gateway', models.GenericIPAddressField(verbose_name='Шлюз')),
                ('metric', models.PositiveIntegerField(default=1, verbose_name='Метрика')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_table', to='equipment.equipment', verbose_name='Оборудование')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.networkinterface', verbose_name='Интерфейс')),
            ],
            options={
                'verbose_name': 'Запись маршрутизации',
                'verbose_name_plural': 'Таблица маршрутизации',
            },
        ),
        migrations.RemoveField(
            model_name='networkinterface',
            name='vlan',
        ),
        migrations.CreateModel(
            name='VLANConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tagged', models.BooleanField(default=True, verbose_name='Tagged')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_configurations', to='networks.networkinterface', verbose_name='Интерфейс')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.vlan', verbose_name='VLAN')),
            ],
            options={
                'verbose_name': 'Конфигурация VLAN',
                'verbose_name_plural': 'Конфигурации VLAN',
                'unique_together': {('interface', 'vlan')},
            },
        ),
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ACL')),
                ('sequence', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('action', models.CharField(choices=[('permit', 'Permit'), ('deny', 'Deny')], max_length=10, verbose_name='Действие')),
                ('protocol', models.CharField(choices=[('ip', 'IP'), ('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP')], default='ip', max_length=10, verbose_name='Протокол')),
                ('source_network', models.CharField(blank=True, max_length=43, verbose_name='Источник')),
                ('destination_network', models.CharField(blank=True, max_length=43, verbose_name='Назначение')),
                ('source_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт источника')),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт назначения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'ACL',
                'verbose_name_plural': 'ACLs',
                'ordering': ['name', 'sequence'],
                'unique_together': {('equipment', 'name', 'sequence')},
            },
        ),
    ]
