# Generated by Django 4.2.14 on 2025-09-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_communicationpost_description'),
        ('equipment', '0022_equipment_ip_addresses_equipment_network_interfaces_and_more'),
        ('networks', '0010_networkinterface_access_vlan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.division', verbose_name='Подразделение')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility', verbose_name='Объект')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='networks.communicationnetwork', verbose_name='Сеть')),
            ],
            options={
                'verbose_name': 'Принадлежность сети',
                'verbose_name_plural': 'Принадлежности сетей',
                'unique_together': {('network', 'division', 'facility', 'equipment')},
            },
        ),
    ]
