# Generated by Django 4.2.14 on 2025-09-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0011_networkmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationnetwork',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='communicationnetwork',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='communicationnetwork',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='communicationnetwork',
            name='subdivisions',
        ),
    ]
