# Generated by Django 4.2.14 on 2025-09-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0012_remove_communicationnetwork_divisions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пропускная способность (Mbps)')),
                ('latency', models.PositiveIntegerField(blank=True, null=True, verbose_name='Задержка (ms)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('from_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_directions', to='networks.networkmembership', verbose_name='Откуда (источник)')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='networks.communicationnetwork', verbose_name='Сеть')),
                ('to_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_directions', to='networks.networkmembership', verbose_name='Куда (назначение)')),
            ],
            options={
                'verbose_name': 'Направление сети',
                'verbose_name_plural': 'Направления сетей',
                'unique_together': {('network', 'from_membership', 'to_membership')},
            },
        ),
    ]
