# Generated by Django 4.2.14 on 2026-02-04 04:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0030_alter_communicationpost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employees.models.employee_photo_path, verbose_name='Фотография')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('rank', models.CharField(max_length=20, null=True, verbose_name='Звание')),
                ('order_rank', models.CharField(blank=True, max_length=30, null=True, verbose_name='Приказ на присвоение звания')),
                ('personal_number', models.CharField(max_length=15, null=True, verbose_name='Личный номер')),
                ('personal_phone', models.CharField(max_length=50, null=True, verbose_name='Телефон')),
                ('work_phone', models.CharField(max_length=50, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата контракта')),
                ('form_state_secrets', models.CharField(blank=True, max_length=15, null=True, verbose_name='Форма гостайны')),
                ('number_state_secrets', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер допуска')),
                ('data_state_secrets', models.DateField(blank=True, null=True, verbose_name='Дата допуска')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень образования')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение')),
                ('year_graduation', models.DateField(blank=True, null=True, verbose_name='Дата окончания учебного заведения')),
                ('date_start_work', models.DateField(blank=True, null=True, verbose_name='Дата начала службы')),
                ('date_end_work', models.DateField(blank=True, null=True, verbose_name='Дата окончания контракта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('is_sha_worker', models.BooleanField(default=False, verbose_name='ШаРаботник')),
                ('is_material_responsible', models.BooleanField(default=False, verbose_name='МОЛ')),
                ('category', models.CharField(choices=[('management', 'Руководство'), ('officer', 'Офицер'), ('warrant_officer', 'Прапорщик'), ('civilian', 'Гражданский персонал')], default='civilian', max_length=20, verbose_name='Категория')),
                ('subcategory', models.CharField(blank=True, choices=[('chief', 'Главный руководитель'), ('deputy_chief', 'Заместитель главного руководителя'), ('department_head', 'Начальник отдела'), ('deputy_department_head', 'Заместитель начальника отдела'), ('section_head', 'Начальник отделения')], max_length=25, null=True, verbose_name='Подкатегория')),
                ('priority', models.IntegerField(default=0, help_text='Чем меньше число, тем выше приоритет', verbose_name='Приоритет сортировки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='facilities.division', verbose_name='Подразделение')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='facilities.subdivision', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['priority', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ShaWorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('access_level', models.CharField(choices=[('1', '1 класс'), ('2', '2 класс')], max_length=1, verbose_name='Форма допуска')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sha_details', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Детали ШаРаботника',
                'verbose_name_plural': 'Детали ШаРаботников',
            },
        ),
        migrations.CreateModel(
            name='ShaEquipmentConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=255, verbose_name='Тип техники')),
                ('conclusion_number', models.CharField(max_length=255, verbose_name='Номер заключения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha_worker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_conclusions', to='employees.shaworkerdetails', verbose_name='ШаРаботник')),
            ],
            options={
                'verbose_name': 'Заключение на технику',
                'verbose_name_plural': 'Заключения на технику',
                'ordering': ['conclusion_number'],
            },
        ),
    ]
