# Generated by Django 4.2.14 on 2026-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('chief', 'Главный руководитель'), ('deputy_chief', 'Заместитель главного руководителя'), ('department_head', 'Начальник отдела'), ('deputy_department_head', 'Заместитель начальника отдела'), ('section_head', 'Начальник отделения'), ('deputy_section_head', 'Заместитель начальника отделения')], max_length=25, null=True, verbose_name='Подкатегория'),
        ),
    ]
