# Generated by Django 4.2.14 on 2026-08-29 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('event_type', models.CharField(choices=[('duty', 'Дежурство'), ('vacation', 'Отпуск'), ('sick', 'Больничный'), ('hospital', 'Госпиталь'), ('business_trip', 'Командировка'), ('inspection', 'Проверка'), ('day_off', 'Отгул'), ('study_leave', 'Учебный отпуск')], max_length=20, verbose_name='Тип события')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Событие графика',
                'verbose_name_plural': 'События графика',
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
