# Generated by Django 4.2.14 on 2025-02-11 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_acceptance_act_number_facility_comments_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Учетная запись', 'verbose_name_plural': 'Учетные записи'},
        ),
        migrations.RemoveField(
            model_name='shaequipmentconclusion',
            name='sha_details',
        ),
        migrations.RemoveField(
            model_name='shaworkerdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_material_responsible',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sha_worker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subdivision',
        ),
        migrations.AddField(
            model_name='shaequipmentconclusion',
            name='sha_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_conclusions', to='users.shaworkerdetails', verbose_name='ШаРаботник'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('department', models.CharField(max_length=255, verbose_name='Отдел')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('contract_date', models.DateField(verbose_name='Дата контракта')),
                ('subdivision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отделение')),
                ('is_sha_worker', models.BooleanField(default=False, verbose_name='ШаРаботник')),
                ('is_material_responsible', models.BooleanField(default=False, verbose_name='МОЛ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='facilities.division', verbose_name='Подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='users.user', verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='shaworkerdetails',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sha_details', to='users.employee', verbose_name='Сотрудник'),
        ),
    ]
