# Generated by Django 4.2.14 on 2025-02-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_acceptance_act_number_facility_comments_and_more'),
        ('users', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='facilities.division', verbose_name='Подразделение'),
        ),
    ]
