# Generated by Django 4.2.14 on 2025-02-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='personal_phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
