# Generated by Django 4.2.14 on 2025-02-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_phone_employee_personal_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaequipmentconclusion',
            name='sha_worker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_conclusions', to='users.shaworkerdetails', verbose_name='ШаРаботник'),
        ),
        migrations.AlterField(
            model_name='shaworkerdetails',
            name='employee',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sha_details', to='users.employee', verbose_name='Сотрудник'),
        ),
    ]
