# Generated by Django 4.2.14 on 2025-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_shaequipmentconclusion_sha_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.CharField(max_length=255, null=True, verbose_name='Звание'),
        ),
    ]
