# Generated by Django 4.2.14 on 2025-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employee_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order_rank',
            field=models.CharField(max_length=255, null=True, verbose_name='Приказ на присвоение звания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Личный номер'),
        ),
    ]
