# Generated by Django 4.2.14 on 2025-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_employee_order_rank_employee_personal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(max_length=50, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_state_secrets',
            field=models.CharField(max_length=15, null=True, verbose_name='Форма гостайны'),
        ),
        migrations.AddField(
            model_name='employee',
            name='institution',
            field=models.CharField(max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_state_secrets',
            field=models.DateField(null=True, verbose_name='Дата допуска'),
        ),
        migrations.AddField(
            model_name='employee',
            name='year_graduation',
            field=models.DateField(null=True, verbose_name='Дата окончания учебного заведения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=14, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='order_rank',
            field=models.CharField(max_length=20, null=True, verbose_name='Приказ на присвоение звания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Личный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=32, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(max_length=20, null=True, verbose_name='Звание'),
        ),
    ]
