# Generated by Django 4.2.14 on 2025-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employee_education_employee_form_state_secrets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(null=True, verbose_name='Комментарии'),
        ),
    ]
