# Generated by Django 4.2.14 on 2025-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_end_job',
            field=models.DateField(null=True, verbose_name='Дата окончания контракта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_job',
            field=models.DateField(null=True, verbose_name='Дата начала службы'),
        ),
    ]
