# Generated by Django 4.2.14 on 2025-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_date_end_job_employee_date_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_end_job',
            new_name='date_end_work',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_job',
            new_name='date_start_work',
        ),
        migrations.AddField(
            model_name='employee',
            name='data_state_secrets',
            field=models.DateField(null=True, verbose_name='Дата допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number_state_secrets',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер допуска'),
        ),
    ]
