# Generated by Django 4.2.14 on 2025-03-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_date_end_job_employee_date_end_work_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['priority', 'full_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('management', 'Руководство'), ('officer', 'Офицер'), ('warrant_officer', 'Прапорщик'), ('civilian', 'Гражданский персонал')], default='civilian', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше приоритет', verbose_name='Приоритет сортировки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('chief', 'Главный руководитель'), ('deputy_chief', 'Заместитель главного руководителя'), ('department_head', 'Начальник отдела'), ('deputy_department_head', 'Заместитель начальника отдела'), ('section_head', 'Начальник отделения')], max_length=25, null=True, verbose_name='Подкатегория'),
        ),
    ]
