# Generated by Django 4.2.14 on 2025-03-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_division_staff_civilians_division_staff_command_and_more'),
        ('users', '0013_alter_employee_options_employee_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='data_state_secrets',
            field=models.DateField(blank=True, null=True, verbose_name='Дата допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_end_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_start_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала службы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='form_state_secrets',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Форма гостайны'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number_state_secrets',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='order_rank',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Приказ на присвоение звания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Личный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='facilities.subdivision', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='year_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания учебного заведения'),
        ),
    ]
