# Generated by Django 4.2.14 on 2025-03-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_command',
            field=models.BooleanField(default=False, verbose_name='Является руководством'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('management', 'Руководство'), ('officer', 'Офицер'), ('warrant_officer', 'Прапорщик'), ('civilian', 'Гражданский персонал')], max_length=20, verbose_name='Категория'),
        ),
    ]
