# Generated by Django 4.2.14 on 2025-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_employee_is_command_alter_employee_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_command',
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('management', 'Руководство'), ('officer', 'Офицер'), ('warrant_officer', 'Прапорщик'), ('civilian', 'Гражданский персонал')], default='civilian', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_date',
            field=models.DateField(null=True, verbose_name='Дата контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='data_state_secrets',
            field=models.DateField(null=True, verbose_name='Дата допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_end_work',
            field=models.DateField(null=True, verbose_name='Дата окончания контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_start_work',
            field=models.DateField(null=True, verbose_name='Дата начала службы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=14, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(max_length=50, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='form_state_secrets',
            field=models.CharField(max_length=15, null=True, verbose_name='Форма гостайны'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='institution',
            field=models.CharField(max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number_state_secrets',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='order_rank',
            field=models.CharField(max_length=20, null=True, verbose_name='Приказ на присвоение звания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Личный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(max_length=20, null=True, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='year_graduation',
            field=models.DateField(null=True, verbose_name='Дата окончания учебного заведения'),
        ),
    ]
