# Generated by Django 4.2.14 on 2025-03-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_division_staff_actual_division_staff_planned_and_more'),
        ('users', '0016_remove_employee_is_command_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='facilities.subdivision', verbose_name='Отделение'),
        ),
    ]
