# Generated by Django 4.2.14 on 2025-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_employee_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_material_responsible',
            field=models.BooleanField(default=False, null=True, verbose_name='МОЛ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_sha_worker',
            field=models.BooleanField(default=False, null=True, verbose_name='ШаРаботник'),
        ),
    ]
