# Generated by Django 4.2.14 on 2025-04-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_employee_is_material_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
