# Generated by Django 4.2.14 on 2025-04-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_remove_division_staff_actual_and_more'),
        ('users', '0020_remove_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='facilities.division', verbose_name='Подразделение'),
        ),
    ]
