# Generated by Django 4.2.14 on 2025-04-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_remove_division_staff_actual_and_more'),
        ('users', '0021_alter_employee_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='facilities.division', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='facilities.subdivision', verbose_name='Отделение'),
        ),
    ]
