# Generated by Django 4.2.14 on 2025-04-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_alter_subdivision_division'),
        ('users', '0022_alter_employee_division_alter_employee_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='facilities.division', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='facilities.subdivision', verbose_name='Отделение'),
        ),
    ]
