# Generated by Django 4.2.14 on 2025-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='order_rank',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Приказ на присвоение звания'),
        ),
    ]
