# Generated by Django 4.2.14 on 2025-07-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_managers_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='data_state_secrets',
            field=models.DateField(blank=True, null=True, verbose_name='Дата допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_end_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания контракта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_start_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала службы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='form_state_secrets',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Форма гостайны'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number_state_secrets',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='year_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания учебного заведения'),
        ),
    ]
