# Generated by Django 4.2.14 on 2025-08-03 06:34

from django.db import migrations, models
def employee_photo_path(instance, filename):
    import os
    from django.utils.timezone import now
    ext = filename.split('.')[-1]
    filename = f'{now().strftime("%Y%m%d%H%M%S")}_{instance.id}.{ext}'
    return os.path.join('employees/photos', filename)



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=employee_photo_path, verbose_name='Фотография'),        ),
    ]
