# Generated by Django 4.2.14 on 2025-10-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_communicationpost_description'),
        ('users', '0033_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='facilities.division', verbose_name='Подразделение пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='facilities.subdivision', verbose_name='Отделение пользователя'),
        ),
    ]
