# Generated by Django 4.2.14 on 2025-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_user_division_user_user_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_global_view',
            field=models.BooleanField(default=False, verbose_name='Глобальный режим просмотра'),
        ),
    ]
