# Generated by Django 4.2.14 on 2026-01-25 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_is_global_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('download', 'Скачивание'), ('upload', 'Загрузка'), ('export', 'Экспорт'), ('import', 'Импорт'), ('approve', 'Утверждение'), ('reject', 'Отклонение'), ('move', 'Перемещение'), ('copy', 'Копирование'), ('archive', 'Архивирование'), ('restore', 'Восстановление')], max_length=20, verbose_name='Действие')),
                ('module', models.CharField(choices=[('employees', 'Сотрудники'), ('equipment', 'Оборудование'), ('facilities', 'Объекты'), ('tasks', 'Задачи'), ('networks', 'Сети связи'), ('users', 'Пользователи'), ('divisions', 'Подразделения'), ('subdivisions', 'Отделения'), ('auth', 'Аутентификация'), ('system', 'Система'), ('storage', 'Хранилище'), ('sha_workers', 'ШаРаботники'), ('sha_equipment', 'ШаОборудование'), ('reports', 'Отчеты'), ('settings', 'Настройки')], max_length=20, verbose_name='Модуль')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID объекта')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название объекта')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='Детали действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип файла')),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место хранения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действий пользователя',
                'verbose_name_plural': 'Логи действий пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_usera_user_id_835fca_idx'), models.Index(fields=['action', 'created_at'], name='users_usera_action_68a535_idx'), models.Index(fields=['module', 'created_at'], name='users_usera_module_41ae74_idx'), models.Index(fields=['storage_location'], name='users_usera_storage_4de976_idx'), models.Index(fields=['file_type'], name='users_usera_file_ty_16b2ba_idx')],
            },
        ),
    ]
