# Generated by Django 4.2.14 on 2026-02-04 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('equipment', '0028_alter_equipment_assigned_to'),
        ('users', '0036_useractionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shaequipmentconclusion',
            name='sha_worker',
        ),
        migrations.RemoveField(
            model_name='shaworkerdetails',
            name='employee',
        ),
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ShaEquipmentConclusion',
        ),
        migrations.DeleteModel(
            name='ShaWorkerDetails',
        ),
    ]
