# Generated by Django 4.2.14 on 2026-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_shaequipmentconclusion_sha_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('download', 'Скачивание'), ('upload', 'Загрузка'), ('export', 'Экспорт'), ('import', 'Импорт'), ('move', 'Перемещение'), ('copy', 'Копирование'), ('archive', 'Архивирование'), ('restore', 'Восстановление'), ('decommission', 'Списание')], max_length=20, verbose_name='Действие'),
        ),
    ]
