# Generated by Django 4.2.14 on 2026-04-05 08:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0038_alter_useractionlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Группа-роль',
                'verbose_name_plural': 'Группы-роли',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='2FA код (4 цифры)'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA включена'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='module',
            field=models.CharField(choices=[('auth', 'Аутентификация'), ('users', 'Пользователи'), ('employees', 'Сотрудники'), ('equipment', 'Оборудование'), ('divisions', 'Подразделения'), ('networks', 'Сети связи'), ('tasks', 'Задачи'), ('storage', 'Хранилище'), ('maps', 'Карты'), ('organs', 'Органы'), ('system', 'Система')], max_length=20, verbose_name='Модуль'),
        ),
    ]
